global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: "kafka"
    static_configs:
      - targets:
          - "<INTERNAL-VM-IP-1>:8080"
          - "<INTERNAL-VM-IP-2>:8080"
          - "<INTERNAL-VM-IP-3>:8080"
